Crash fixes and updates.
Fix crash at launch by removing ads.
Fix NoClassDefFoundError at GameField start by exporting AndEngine libs.
Ignore gen directory and unignore .gitignore.
Changes from updated Android SDK.